# Basic
title: å°å…µç¦…ï¼ˆé™†å»¶æ°ï¼‰çš„æŠ€æœ¯åšå®¢
subtitle: ä¸ªäººç«™
description: æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººç«™~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: é™†å»¶æ°
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: è¿ç»´å¼€å‘ / å®¹å™¨ / äº‘å­˜å‚¨ / è™šæ‹ŸåŒ–
repository: xiaobingchan/xiaobingchan.github.io
github_url: https://github.com/xiaobingchan
url: https://xiaobingchan.github.io

# Comment
comment:
    disqus: è¿ç»´å¼€å‘ / å®¹å™¨ / äº‘å­˜å‚¨ / è™šæ‹ŸåŒ–
    # gitment: xxx // éœ€è¦ä¿®æ”¹ comments.htmlä¸­çš„client_idå’Œclient_secret
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    weixin: 1755337994 
    github: xiaobingchan
    zhihu: lu-yan-jie-31
    juejin: 5da948c7518825647c51439e
    jianshu: 9ffcc1aece2f
    mail: luyanjie4@gmail.com


# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: 63dcbeebcd3e20126f7d54999b5d271b

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: UA-150373352-1  
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºæˆ‘, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


